const themes = [
  {
    name: "dark",
    colorBg: "var(--bg-color)",
    colorBg2: "var(--bg-color-accent)",
    colorSuccess: "var(--success)",
    colorWarning: "var(--warning)",
    colorDanger: "var(--danger)",
    colorGradient: "linear-gradient(110.42deg, #CF57A3 29.2%, #4731B6 63.56%)",
    colorGreenDark: "var(--link-color-accent)",
    colorGreenLight: "var(--link-color)",
    activeNavLink: "var(--bg-color)",
    activeNavLinkHover: "rgba(249,249,249, 0.03)",
    colorPrimary: "#7263F3",
    colorGreyDark: "#131313",
    color1: "var(--text-color)",
    color2: "#dbe1e8",
    btnColor1: "var(--second-color)",
    colorGrey2: "#b2becd",
    colorGrey3: "#6c7983",
    colorGrey5: "#2a2e35",
    colorWhite: "#fff",
    colorPrimaryGreen: "#6FCF97",
    borderColor: "var(--second-color)",
    borderColor2: "var(--primary-color)",
    shadow7: "1px 2px 5px var(--text-color)",
    sidebarWidth: "15rem",
    colorIcons: "var(--nav-color)",
    colorIcons2: "var(--link-color)",
  },
  {
    name: "light",
    colorBg: "var(--bg-color)",
    colorBg2: "var(--bg-color-accent)",
    colorSuccess: "var(--success)",
    colorWarning: "var(--warning)",
    colorDanger: "var(--danger)",
    colorGradient: "linear-gradient(110.42deg, #CF57A3 29.2%, #4731B6 63.56%)",
    colorGreenDark: "var(--link-color-accent)",
    colorGreenLight: "var(--link-color)",
    activeNavLink: "var(--bg-color)",
    activeNavLinkHover: "#C5C5C5",
    colorPrimary: "#7263F3",
    colorGreyDark: "#131313",
    color1: "var(--text-color)",
    color2: "#dbe1e8",
    btnColor1: "var(--second-color)",
    colorGrey2: "#b2becd",
    colorGrey3: "#6c7983",
    colorGrey5: "#2a2e35",
    colorWhite: "#fff",
    borderRadiusMd: "12px",
    borderRadiusMd2: "15px",
    borderColor: "var(--second-color)",
    borderColor2: "var(--primary-color)",
    shadow7: "1px 2px 5px var(--text-color)",
    sidebarWidth: "15rem",
    colorIcons: "var(--nav-color)",
    colorIcons2: "var(--link-color)",
  },
];
export default themes;